# vim:ft=kitty
## name: Noctis (EVA Mark.06 High Contrast)
## based on the Noctis theme family (MIT, Liviu Schera)

foreground #000000
background #ffffff
selection_foreground #000000
selection_background #b098f7
cursor #ff3d00
cursor_text_color #ffffff
url_color #066174

active_border_color #6a3df0
inactive_border_color #535770
bell_border_color #943d00

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #ffffff
active_tab_background #6a3df0
inactive_tab_foreground #3a5bd9
inactive_tab_background #ffffff
tab_bar_background #ffffff

mark1_foreground #ffffff
mark1_background #284acd
mark2_foreground #ffffff
mark2_background #7d10d5
mark3_foreground #ffffff
mark3_background #066174

color0 #2a2d40
color1 #af1030
color2 #0b653a
color3 #943d00
color4 #284acd
color5 #7d10d5
color6 #066174
color7 #4e5677
color8 #535770
color9 #b10e27
color10 #1b643f
color11 #8a4400
color12 #1544e3
color13 #7a00e5
color14 #155e6b
color15 #ffffff
