# vim:ft=kitty
## name: Noctis (MAGI OLED)
## based on the Noctis theme family (MIT, Liviu Schera)

foreground #ffc27a
background #000000
selection_foreground #ffc27a
selection_background #662a00
cursor #ffb000
cursor_text_color #000000
url_color #19d3c5

active_border_color #ff6a00
inactive_border_color #5c4028
bell_border_color #ff9f1a

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #000000
active_tab_background #ff6a00
inactive_tab_foreground #4dd8ff
inactive_tab_background #000000
tab_bar_background #000000

mark1_foreground #000000
mark1_background #4d9bff
mark2_foreground #000000
mark2_background #c96bff
mark3_foreground #000000
mark3_background #19d3c5

color0 #1f130b
color1 #ff2a2a
color2 #3dffa8
color3 #ff9f1a
color4 #4d9bff
color5 #c96bff
color6 #19d3c5
color7 #e8cfae
color8 #5c4028
color9 #ff5c4d
color10 #7dffc4
color11 #ffc247
color12 #85bbff
color13 #dd9bff
color14 #66eee0
color15 #ffffff
