# vim:ft=kitty
## name: Noctis (EVA-08)
## based on the Noctis theme family (MIT, Liviu Schera)

foreground #ffe6f8
background #16051a
selection_foreground #ffe6f8
selection_background #641347
cursor #21e6ff
cursor_text_color #16051a
url_color #21e6ff

active_border_color #ff2fa0
inactive_border_color #663a66
bell_border_color #ffb400

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #000000
active_tab_background #ff2fa0
inactive_tab_foreground #21e6ff
inactive_tab_background #16051a
tab_bar_background #0f0312

mark1_foreground #000000
mark1_background #6aa8ff
mark2_foreground #000000
mark2_background #ff2fa0
mark3_foreground #000000
mark3_background #21e6ff

color0 #2a0d2c
color1 #ff3d6e
color2 #4dffc0
color3 #ffb400
color4 #6aa8ff
color5 #ff2fa0
color6 #21e6ff
color7 #f0d0ea
color8 #663a66
color9 #ff6f96
color10 #8affd8
color11 #ffd24d
color12 #95c0ff
color13 #ff70c4
color14 #7af0ff
color15 #ffffff
